# Generated by Django 4.0.4 on 2022-05-13 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_uuid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('token_name', models.CharField(max_length=32, unique=True)),
                ('token_sym', models.CharField(max_length=5, unique=True)),
                ('token_img', models.URLField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(max_length=254, unique=True)),
                ('user_f_name', models.CharField(max_length=32)),
                ('user_l_name', models.CharField(max_length=32)),
                ('user_dob', models.DateField()),
                ('user_last_access', models.DateTimeField(auto_now_add=True)),
                ('user_active', models.BooleanField(default=False)),
                ('user_created', models.DateTimeField(auto_now_add=True)),
                ('user_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('price_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price_timestamp', models.CharField(max_length=128)),
                ('price_value', models.FloatField()),
                ('price_token_uuid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CryptoWizard.token')),
            ],
        ),
        migrations.CreateModel(
            name='Password',
            fields=[
                ('pw_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('pw_encr_str', models.CharField(max_length=254)),
                ('pw_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CryptoWizard.user')),
            ],
        ),
    ]
